
services:
  consumer:
    image: ./consumer_bk
    build:
      context: ./consumer_bk
    networks:
      - ms-test

  producer:
    image: ./producer_bk
    container_name: producer_bk
    build:
      context: ./producer_bk
    networks:
      - ms-test

  rabbitmq:
    image: rabbitmq
    ports:  
      - "5672:5672" 
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: user 
      RABBITMQ_DEFAULT_PASS: password 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
    networks:
      - ms-test

networks:
  ms-test:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local
