version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ms-test

  producer:
    build:
      context: ./producer_bk
    container_name: producer_bk
    ports:
      - "5001:5001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    networks:
      - ms-test

  consumer:
    build:
      context: ./consumer_bk
    container_name: consumer_bk
    ports:
      - "5002:5002"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    networks:
      - ms-test

networks:
  ms-test:
    driver: bridge

volumes:
  rabbitmq_data: